version: 2

updates:
  - package-ecosystem: npm
    directory: /
    rebase-strategy: auto
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: "scope"
    versioning-strategy: widen

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: "scope"
