version: 2

updates:
  - package-ecosystem: npm
    directory: /
    rebase-strategy: auto
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "*"
        dependency-type: "all"
    commit-message:
      prefix: "chore(deps):"
    versioning-strategy: increase
